#!/usr/bin/env node
/**
 * 合并所有模块的 model 到统一的 model 目录
 * 并更新 API 文件中的导入路径
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const GENERATED_ROOT = path.resolve(__dirname, '../api/generated');
const SHARED_MODEL_DIR = path.join(GENERATED_ROOT, 'model');

function mergeModels() {
  console.log('🔧 开始合并 model 文件...');

  if (!fs.existsSync(GENERATED_ROOT)) {
    console.log('⚠️  generated 目录不存在，跳过处理');
    return;
  }

  // 确保共享 model 目录存在
  if (!fs.existsSync(SHARED_MODEL_DIR)) {
    fs.mkdirSync(SHARED_MODEL_DIR, { recursive: true });
  }

  const modules = fs.readdirSync(GENERATED_ROOT).filter(m => {
    const mPath = path.join(GENERATED_ROOT, m);
    return fs.statSync(mPath).isDirectory() && m !== 'model';
  });

  let mergedCount = 0;
  let updatedCount = 0;

  // 第一步：收集所有 model 文件并合并到共享目录
  const allModelFiles = new Set();

  modules.forEach(moduleName => {
    const moduleModelDir = path.join(GENERATED_ROOT, moduleName, 'model');

    if (fs.existsSync(moduleModelDir)) {
      const modelFiles = fs.readdirSync(moduleModelDir).filter(f => f.endsWith('.ts'));

      modelFiles.forEach(file => {
        const sourcePath = path.join(moduleModelDir, file);
        const targetPath = path.join(SHARED_MODEL_DIR, file);

        // 如果文件不存在，复制到共享目录
        if (!fs.existsSync(targetPath)) {
          fs.copyFileSync(sourcePath, targetPath);
          mergedCount++;
        }

        allModelFiles.add(file);
      });
    }
  });

  console.log(`📦 合并完成: ${mergedCount} 个 model 文件`);

  // 第二步：更新所有 API 文件中的导入路径
  modules.forEach(moduleName => {
    const moduleDir = path.join(GENERATED_ROOT, moduleName);
    const apiFiles = fs.readdirSync(moduleDir).filter(f => f.endsWith('.ts') && f !== 'api.ts');

    apiFiles.forEach(file => {
      const filePath = path.join(moduleDir, file);
      let content = fs.readFileSync(filePath, 'utf-8');

      // 替换 model 导入路径
      // 从 './model/xxx' 改为 '../model/xxx'
      const originalContent = content;
      content = content.replace(/from\s+['"]\.\/model\/([^'"]+)['"]/g, "from '../model/$1'");
      content = content.replace(/from\s+['"]\.\/model['"]/g, "from '../model'");

      if (content !== originalContent) {
        fs.writeFileSync(filePath, content, 'utf-8');
        updatedCount++;
      }
    });

    // 删除模块内的 model 目录
    const moduleModelDir = path.join(moduleDir, 'model');
    if (fs.existsSync(moduleModelDir)) {
      fs.rmSync(moduleModelDir, { recursive: true, force: true });
      console.log(`🗑️  删除: ${moduleName}/model`);
    }
  });

  console.log(`📝 更新完成: ${updatedCount} 个 API 文件`);

  // 第三步：修复 model/index.ts，确保所有类型都被导出
  fixModelIndex();

  console.log(`✨ Model 合并完成，所有类型定义已统一到 model/ 目录`);
}

/**
 * 修复 model/index.ts，确保所有类型都被导出
 */
function fixModelIndex() {
  const indexPath = path.join(SHARED_MODEL_DIR, 'index.ts');

  if (!fs.existsSync(indexPath)) {
    console.log('⚠️  model/index.ts 不存在，跳过修复');
    return;
  }

  // 读取所有 model 文件
  const modelFiles = fs.readdirSync(SHARED_MODEL_DIR)
    .filter(f => f.endsWith('.ts') && f !== 'index.ts')
    .sort();

  // 生成新的 index.ts 内容
  const exports = modelFiles.map(file => {
    const name = file.replace('.ts', '');
    return `export * from './${name}';`;
  });

  const content = `/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * 个人项目
 * OpenAPI spec version: 1.0.0
 */

${exports.join('\n')}
`;

  fs.writeFileSync(indexPath, content, 'utf-8');
  console.log(`🔧 修复 model/index.ts，导出 ${modelFiles.length} 个类型`);
}

mergeModels();
